### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by kosuke55** [kosuke55/hanging_points_generator#2]
### TODO  

**全体** : librayをimportしてros nodeをつくる感じだと良い。
現在はimportしているのはhanging_poits_generatorだけ。icpやtsdfの部分もimport して使うと良い。

- [x] voxelized_meshが重すぎる
隣り合うvoxelの点と面を重複して定義している。
物体の中の点と面をいらない。
https://github.com/kosuke55/hanging_points_generator/blob/master/hanging_points_generator/create_mesh.py#L112-L165
->merge_verticesみたいので頂点はマージできるがどっち道重いので、このmeshを使うならvoxelize -> marching cubesで生成したものを使ったほうがよい。

- [x] voxelized_meshが重すぎる
- [x] Andy Zengさんのtsdfと試してみる

- [ ] フック掛け動作
hanging pointsがocclusionにならないように物体の初期姿勢を決める。
contact pointのassoc位置でik解く->二次元でtrakingしながら位置調整でやってみる。
- [ ] contact point の誤判定対策。
点の多いところ、smoothing、落下待ち時間を長く etc..
- [ ] cupみたいな曲面の物体はicpでづれる。icpのときにはgripperのpointcloudも入れる？
- [ ] contact_pointsのtracking
二次元に投影してtrackingすれば良い。
- [ ] ランダム探索ではなく形状からあたりをつける。
曲線部分に対して円近似して、円弧の角度を求める。

- [x] contact_pointsからposearrayをpublish
- [x] create_mesh.py(ros) -> meshfix.py(3) -> hanging_points_generator.py(2 or 3)  つなげる
python3とどうつなげるか。ファイル読み書き or socket通信?　
-> srvice call からsubuprocessでpython3を実行し、ファイル書き込みで対応した
- [x] contact point はorientationも入れる
棒の方向x, contact point から棒への方向をyとした。
- [x]  launch。save_dir をparamで合わせる。
